nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-TypeQuestion', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/':
            allow-origin: ['localhost']
            allow_headers: ['localhost']
            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE' ]
            max_age: 3600