<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXTrczxd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXTrczxd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXTrczxd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXTrczxd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXTrczxd\App_KernelDevDebugContainer([
    'container.build_hash' => 'XTrczxd',
    'container.build_id' => '2668a151',
    'container.build_time' => 1685709298,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXTrczxd');
