<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6HsbpjT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6HsbpjT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6HsbpjT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6HsbpjT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6HsbpjT\App_KernelDevDebugContainer([
    'container.build_hash' => '6HsbpjT',
    'container.build_id' => '973996dc',
    'container.build_time' => 1678115945,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6HsbpjT');
