<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDDWwPDl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDDWwPDl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDDWwPDl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDDWwPDl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDDWwPDl\App_KernelDevDebugContainer([
    'container.build_hash' => 'DDWwPDl',
    'container.build_id' => '424426ee',
    'container.build_time' => 1678720969,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDDWwPDl');
